# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\__tmp\fix_rotate\object_orient\widgets\dialog.ui',
# licensing of 'D:\work\__tmp\fix_rotate\object_orient\widgets\dialog.ui' applies.
#
# Created: Fri Dec 25 11:54:42 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ObjectOrient(object):
    def setupUi(self, ObjectOrient):
        ObjectOrient.setObjectName("ObjectOrient")
        ObjectOrient.resize(277, 488)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ObjectOrient)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.obj_btp = QtWidgets.QGroupBox(ObjectOrient)
        self.obj_btp.setObjectName("obj_btp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.obj_btp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.set_obj_btn = QtWidgets.QPushButton(self.obj_btp)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.set_obj_btn.setFont(font)
        self.set_obj_btn.setObjectName("set_obj_btn")
        self.verticalLayout_2.addWidget(self.set_obj_btn)
        self.obj_name_lb = QtWidgets.QLabel(self.obj_btp)
        self.obj_name_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.obj_name_lb.setObjectName("obj_name_lb")
        self.verticalLayout_2.addWidget(self.obj_name_lb)
        self.verticalLayout_3.addWidget(self.obj_btp)
        self.orient_grp = QtWidgets.QGroupBox(ObjectOrient)
        self.orient_grp.setObjectName("orient_grp")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.orient_grp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.preview_cbx = QtWidgets.QCheckBox(self.orient_grp)
        self.preview_cbx.setObjectName("preview_cbx")
        self.verticalLayout.addWidget(self.preview_cbx)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.align_btn = QtWidgets.QPushButton(self.orient_grp)
        self.align_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.align_btn.setFont(font)
        self.align_btn.setObjectName("align_btn")
        self.horizontalLayout_2.addWidget(self.align_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.axis_x_btn = QtWidgets.QPushButton(self.orient_grp)
        self.axis_x_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.axis_x_btn.setFont(font)
        self.axis_x_btn.setObjectName("axis_x_btn")
        self.horizontalLayout.addWidget(self.axis_x_btn)
        self.axis_y_btn = QtWidgets.QPushButton(self.orient_grp)
        self.axis_y_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.axis_y_btn.setFont(font)
        self.axis_y_btn.setObjectName("axis_y_btn")
        self.horizontalLayout.addWidget(self.axis_y_btn)
        self.axis_z_btn = QtWidgets.QPushButton(self.orient_grp)
        self.axis_z_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.axis_z_btn.setFont(font)
        self.axis_z_btn.setObjectName("axis_z_btn")
        self.horizontalLayout.addWidget(self.axis_z_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.orient_grp)
        self.transf_grp = QtWidgets.QGroupBox(ObjectOrient)
        self.transf_grp.setObjectName("transf_grp")
        self.gridLayout = QtWidgets.QGridLayout(self.transf_grp)
        self.gridLayout.setObjectName("gridLayout")
        self.z_add_btn = QtWidgets.QPushButton(self.transf_grp)
        self.z_add_btn.setMinimumSize(QtCore.QSize(40, 25))
        self.z_add_btn.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.z_add_btn.setFont(font)
        self.z_add_btn.setObjectName("z_add_btn")
        self.gridLayout.addWidget(self.z_add_btn, 3, 1, 1, 1)
        self.drop_btn = QtWidgets.QPushButton(self.transf_grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drop_btn.sizePolicy().hasHeightForWidth())
        self.drop_btn.setSizePolicy(sizePolicy)
        self.drop_btn.setMinimumSize(QtCore.QSize(60, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drop_btn.setFont(font)
        self.drop_btn.setObjectName("drop_btn")
        self.gridLayout.addWidget(self.drop_btn, 1, 0, 3, 1)
        self.z_sub_btn = QtWidgets.QPushButton(self.transf_grp)
        self.z_sub_btn.setMinimumSize(QtCore.QSize(40, 25))
        self.z_sub_btn.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.z_sub_btn.setFont(font)
        self.z_sub_btn.setObjectName("z_sub_btn")
        self.gridLayout.addWidget(self.z_sub_btn, 3, 3, 1, 1)
        self.set_origin_btn = QtWidgets.QPushButton(self.transf_grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_origin_btn.sizePolicy().hasHeightForWidth())
        self.set_origin_btn.setSizePolicy(sizePolicy)
        self.set_origin_btn.setMinimumSize(QtCore.QSize(60, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.set_origin_btn.setFont(font)
        self.set_origin_btn.setObjectName("set_origin_btn")
        self.gridLayout.addWidget(self.set_origin_btn, 1, 4, 3, 1)
        self.label_3 = QtWidgets.QLabel(self.transf_grp)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.transf_grp)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.transf_grp)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 3)
        self.y_sub_btn = QtWidgets.QPushButton(self.transf_grp)
        self.y_sub_btn.setMinimumSize(QtCore.QSize(40, 25))
        self.y_sub_btn.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y_sub_btn.setFont(font)
        self.y_sub_btn.setObjectName("y_sub_btn")
        self.gridLayout.addWidget(self.y_sub_btn, 2, 3, 1, 1)
        self.y_add_btn = QtWidgets.QPushButton(self.transf_grp)
        self.y_add_btn.setMinimumSize(QtCore.QSize(40, 25))
        self.y_add_btn.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y_add_btn.setFont(font)
        self.y_add_btn.setObjectName("y_add_btn")
        self.gridLayout.addWidget(self.y_add_btn, 2, 1, 1, 1)
        self.x_add_btn = QtWidgets.QPushButton(self.transf_grp)
        self.x_add_btn.setMinimumSize(QtCore.QSize(40, 25))
        self.x_add_btn.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_add_btn.setFont(font)
        self.x_add_btn.setObjectName("x_add_btn")
        self.gridLayout.addWidget(self.x_add_btn, 1, 1, 1, 1)
        self.x_sub_btn = QtWidgets.QPushButton(self.transf_grp)
        self.x_sub_btn.setMinimumSize(QtCore.QSize(40, 25))
        self.x_sub_btn.setMaximumSize(QtCore.QSize(40, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_sub_btn.setFont(font)
        self.x_sub_btn.setObjectName("x_sub_btn")
        self.gridLayout.addWidget(self.x_sub_btn, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.transf_grp)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout_3.addWidget(self.transf_grp)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.freeze_btn = QtWidgets.QPushButton(ObjectOrient)
        self.freeze_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.freeze_btn.setFont(font)
        self.freeze_btn.setObjectName("freeze_btn")
        self.horizontalLayout_3.addWidget(self.freeze_btn)
        self.reset_btn = QtWidgets.QPushButton(ObjectOrient)
        self.reset_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_3.addWidget(self.reset_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.restore_btn = QtWidgets.QPushButton(ObjectOrient)
        self.restore_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.restore_btn.setFont(font)
        self.restore_btn.setObjectName("restore_btn")
        self.verticalLayout_3.addWidget(self.restore_btn)

        self.retranslateUi(ObjectOrient)
        QtCore.QMetaObject.connectSlotsByName(ObjectOrient)

    def retranslateUi(self, ObjectOrient):
        ObjectOrient.setWindowTitle(QtWidgets.QApplication.translate("ObjectOrient", "Object Orient", None, -1))
        self.obj_btp.setTitle(QtWidgets.QApplication.translate("ObjectOrient", "Object", None, -1))
        self.set_obj_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Set Object", None, -1))
        self.obj_name_lb.setText(QtWidgets.QApplication.translate("ObjectOrient", "Object Not Set", None, -1))
        self.orient_grp.setTitle(QtWidgets.QApplication.translate("ObjectOrient", "Orient", None, -1))
        self.preview_cbx.setText(QtWidgets.QApplication.translate("ObjectOrient", "Preview Mode", None, -1))
        self.align_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Align", None, -1))
        self.axis_x_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "X", None, -1))
        self.axis_y_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Y", None, -1))
        self.axis_z_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Z", None, -1))
        self.transf_grp.setTitle(QtWidgets.QApplication.translate("ObjectOrient", "Rotate / Transform", None, -1))
        self.z_add_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "+", None, -1))
        self.drop_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Drop", None, -1))
        self.z_sub_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "-", None, -1))
        self.set_origin_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Origin", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ObjectOrient", "Z", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ObjectOrient", "Y", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ObjectOrient", "Rotate by 90 / 180", None, -1))
        self.y_sub_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "-", None, -1))
        self.y_add_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "+", None, -1))
        self.x_add_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "+", None, -1))
        self.x_sub_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "-", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ObjectOrient", "X", None, -1))
        self.freeze_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Freeze", None, -1))
        self.reset_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Reset", None, -1))
        self.restore_btn.setText(QtWidgets.QApplication.translate("ObjectOrient", "Restore Transform", None, -1))

